### ISSUE TITLE
No images is shown when TeamCity is deployed as non-root context

### ISSUE THREAD

**Issue by VladRassokhin** [dbf256/teamcity-chuck-plugin#1]
If TeamCity deployed with some prefix, e.g. `http://localhost:8111/bs/`, images urls are `http://localhost:8111/plugins/ChuckTeamcityPlugin/_chuck_happy.jpg`, but should be `http://localhost:8111/bs/plugins/ChuckTeamcityPlugin/_chuck_happy.jpg`.
Possible solution: use `<c:url>` for image urls.

**Comment by dbf256** [comment]
Vlad, thanks for your feedback, this issue was fixed.
