### ISSUE TITLE
the build Chuck approves/disapproves build number doesn't match actual

### ISSUE THREAD

**Issue by wormiii** [dbf256/teamcity-chuck-plugin#3]
I've set the build ahead for business reasons.  We are on build #1000 but Chuck is saying he approves build #50.   I think it is actually the 50th build in the queue, but I would prefer it to say 1000 to match the build number I've set.

**Comment by dbf256** [comment]
Thanks, fixed it in 0.5.3.

**Comment by wormiii** [comment]
change looks good, thank you
